### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by selfrefactor** [harish2704/html-scrapper#1]
in package.json are missing

  "underscore": "_",
    "lodash": "_",
//-------------------------
wrong line in the example:
instead of  
var scrapper = require('../');

must be  
var scrapper = require('html-scrapper');

**Comment by harish2704** [comment]
Thanks bro,
I have fixed this in following commits
c19a08679350396b7017282720c282a988df2cf0
ab5c896b6f5e139f0d42bb04ff1ef3afd0cbdb4c
All examples are working now. :)
